const colors = {
  light: {
    background: "#f4f9fa",
    foreground: "#0f1d38",
    card: "#ffffff",
    cardForeground: "#0f1d38",
    primary: "#1e3a5f",
    primaryForeground: "#f8fafc",
    secondary: "#0f8b8d",
    secondaryForeground: "#ffffff",
    muted: "#f0f4f8",
    mutedForeground: "#697586",
    accent: "#e8f4f8",
    accentForeground: "#1e3a5f",
    border: "#dce6f0",
    inputBackground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    warning: "#f59e0b",
    gradientStart: "#1e3a5f",
    gradientMid: "#1a6b8a",
    gradientEnd: "#0f8b8d",
    tabBar: "#ffffff",
    headerBackground: "#ffffff",
  },
  dark: {
    background: "#0f1d38",
    foreground: "#f0f4f8",
    card: "#162040",
    cardForeground: "#f0f4f8",
    primary: "#0f8b8d",
    primaryForeground: "#ffffff",
    secondary: "#1a6b8a",
    secondaryForeground: "#ffffff",
    muted: "#1a2848",
    mutedForeground: "#8ea2b8",
    accent: "#1e3a5f",
    accentForeground: "#f0f4f8",
    border: "#1e3a5f",
    inputBackground: "#162040",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    warning: "#f59e0b",
    gradientStart: "#0a1628",
    gradientMid: "#0d3d5a",
    gradientEnd: "#0f8b8d",
    tabBar: "#0f1d38",
    headerBackground: "#0f1d38",
  },
  radius: 10,
};

export default colors;
